version: '3.1'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      - /opt/nest_temperature_forwarder/influxdb:/var/lib/influxdb
    networks:
     - proxy
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M

  # telegraf:
  #   image: telegraf:latest
  #   volumes:
  #     - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    networks:
     - proxy
    deploy:
      replicas: 1
      labels:
       - com.df.notify=true
       - com.df.distribute=true
       - com.df.httpsOnly=true
       - com.df.serviceDomain=grafana.smirlwebs.com
       - com.df.srcPort.1=443
       - com.df.srcPort.2=80
       - com.df.port=3000
       - com.df.letsencrypt.host=grafana.smirlwebs.com
       - com.df.letsencrypt.email=smirlie@googlemail.com
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M

networks:
  proxy:
    external: true
