version: '3.1'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: nest_temperature_forwarder
      INFLUXDB_REPORTING_DISABLED: 'false'
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'
      INFLUXDB_ADMIN_USER: 'admin'
      INFLUXDB_READ_USER: 'reader'
      INFLUXDB_WRITE_USER: 'writer'
    volumes:
      - './init-influxdb.sh:/init-influxdb.sh'
      - './influxdb:/var/lib/influxdb'
    networks:
     - proxy
    secrets:
     - influxdb_admin_password
     - influxdb_read_user_password
     - influxdb_write_user_password
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M

  cron:
    image: registry.smirlwebs.com/smirl/nest_temperature_forwarder:1.3.0
    volumes:
      - .:/opt/code
    networks:
      - proxy
    secrets:
      - nest_access_token
      - influxdb_write_user_password


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource'
    networks:
     - proxy
    volumes:
      - './grafana:/var/lib/grafana'
    deploy:
      replicas: 1
      labels:
       - com.df.notify=true
       - com.df.distribute=true
       - com.df.httpsOnly=true
       - com.df.serviceDomain=grafana.smirlwebs.com
       - com.df.srcPort.1=443
       - com.df.srcPort.2=80
       - com.df.port=3000
       - com.df.letsencrypt.host=grafana.smirlwebs.com
       - com.df.letsencrypt.email=smirlie@googlemail.com
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M

networks:
  proxy:
    external: true

secrets:
  nest_access_token:
    external: true
  influxdb_admin_password:
    external: true
  influxdb_read_user_password:
    external: true
  influxdb_write_user_password:
    external: true
