{
 "title": "Home",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sample",
    "query": "5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Thermostat",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Inside Temperature",
     "groupBy": [
      { "params": [ "$sample" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ambient_temperature_c",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Target",
     "groupBy": [
      { "params": [ "$sample" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "target_temperature_c",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Eco Temperature",
     "groupBy": [
      { "params": [ "$sample" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "eco_temperature_low_c",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Mode:$tag_hvac_mode  State:$tag_hvac_state",
     "groupBy": [
      { "params": [ "$sample" ], "type": "time" },
      { "params": [ "hvac_mode" ], "type": "tag" },
      { "params": [ "hvac_state" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "thermostat_state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Outside Temperature",
     "groupBy": [
      { "params": [ "$sample" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temp_c" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heating - Current Range",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "format": "m",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "thermostat_state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "*5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hvac_state", "operator": "=", "value": "heating" }
     ]
    }
   ]
  },
  {
   "title": "Heating - Past Day",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "format": "m",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$sample" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "thermostat_state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "*5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hvac_state", "operator": "=", "value": "heating" }
     ]
    }
   ]
  },
  {
   "title": "Heating - Past Week",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "format": "m",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$sample" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "thermostat_state",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "*5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hvac_state", "operator": "=", "value": "heating" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}