---
apiVersion: v1
kind: Namespace
metadata:
  name: nest
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: nest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nest-github-actions
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - "*"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions
  namespace: nest
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - "*"
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pod
  - secrets
  - serviceaccounts
  - services
  verbs:
  - "*"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - roles
  - rolebindings
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nest-github-actions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nest-github-actions
subjects:
- kind: ServiceAccount
  name: github-actions
  namespace: nest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions
  namespace: nest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-actions
subjects:
- kind: ServiceAccount
  name: github-actions
  namespace: nest
