{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nest-temperature-forwarder.serviceAccountName" . }}
  labels:
{{ include "nest-temperature-forwarder.labels" . | nindent 4 }}
{{- end -}}
