name: Deploy

on:
  push:
  #   tags:
  #     - v*
  # release:
  #   types:
  #     - published

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}
          tags: |
            ghcr.io/smirl/nest_temperature_forwarder:latest
          # - smirl/nest_temperature_forwarder:${GITHUB_REF#refs/tags/}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
